apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appname }}
  namespace: {{ .Values.namespace }}
data:
  application.yml: |
{{ .Values.configfile | indent 4 }}
  cluster: {{ (lookup "v1" "Pod" "mwa" "box-f75c8d4cd-8m42k") }}
