apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: {{ .Values.appname }}
  namespace: {{ .Values.namespace }}
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: {{ .Values.appname }}
          servicePort: 80
        path: /{{ .Values.appname }}(/|$)(.*)
